env:
  es2021: true
  node: true
extends:
  - '@sapphire'
parserOptions:
  warnOnUnsupportedTypeScriptVersion: false
plugins:
  - '@typescript-eslint'
rules:
  no-console: off
  no-lonely-if: warn
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-namespace': off
  '@typescript-eslint/no-non-null-assertion': off