// Generated by dts-bundle-generator v6.2.0

import { ApplicationCommandData, CommandInteraction } from 'discord.js';

export declare class TagParser {
	parsingRegExp: RegExp;
	parseData(name: string, description: string, options: string, response: string): {
		data: ApplicationCommandData;
		response: string;
	};
	parseResponse(response: string, interaction: CommandInteraction): Promise<void>;
	private parseOptions;
}
export declare class ParsingError extends Error {
	identifier: string;
	readonly name = "ParsingError";
	constructor(options: UserError.Options);
}
export declare namespace UserError {
	interface Options {
		identifier: string;
		message?: string;
	}
}

export {};
